### ISSUE TITLE
[mapsapi] - base configuration for batch API

### ISSUE THREAD

**Issue by sabman** [sabman/cartodb-docker-fork#3]
@mnzaki so upon more investigation of trying to run the Analysis Tools - the following issue seems to be related to the configuration of the Batch API in `mapsapi` service. To reproduce try the following for the user:

`dev@acme.org` I'll message you the pass

![screenflow](https://user-images.githubusercontent.com/1907/48660640-4a109f80-ea65-11e8-804d-a101474ad5df.gif)

Error is:
```json
{"type":"analysis","message":"Unable to enqueue SQL API batch job","analysis":{"id":"a1","type":"moran"}}
```

Current analysis config block has:
```json
"analysis": {
    "batch": {
      "endpoint": "http://127.0.0.1:8080/api/v2/sql/job",
      "hostHeaderTemplate": "{{=it.username}}.localhost.lan"
    },
  },
```

I think it should be 
```json
"analysis": {
    "batch": {
      "endpoint": "http://0.0.0.0:8080/api/v2/sql/job",
      "hostHeaderTemplate": "{{=it.username}}.localhost.lan"
    },
  },
```
I'm not sure exactly what `hostHeaderTemplate` should be but I suspect it doesn't matter yet since we are using the IP to reference the host for now. What do you think?

Also when you first load the map you will see the client services error too.

**Comment by sabman** [comment]
OK Just changed it on the server and rebuild and restarted the image but no joy. 😢

**Comment by mnzaki** [comment]
I believe that endpoint should be the sqlapi endpoint, or actually just the router (so that the port can be avoided). I changed it to point be `http://cartodb-router/api/v2/sql/job` and want to give it a go.
I also looked for `hostHeaderTemplate` in the windshaft code, and it's unclear what it is used for. It's also left as .localhost.lan in the production config provided with windshaft.
